nome = input("Qual è il tuo nome? ")
print("Ciao", nome)
print()
print("Vogliamo sapere se ti piace programmare!")
print("Ti piace programmare?")
risposta = input()
print("Bene, hai scritto:", risposta)